#pragma once

// Auto-generated from cube.vert.glsl
// Do not edit this file manually

const char* const CUBE_VERTEX_SHADER = "#version 330 core\n\nlayout(location = 0) in vec3 position;\nlayout(location = 1) in vec3 color;\n\nout vec3 fragColor;\n\nuniform mat4 mvp;\n\nvoid main()\n{\n    gl_Position = mvp * vec4(position, 1.0);\n    fragColor = color;\n}";
