#pragma once

// Auto-generated from cube.vert.glsl
// Do not edit this file manually

const char* const CUBE_VERTEX_SHADER = "#version 330 core\n\nlayout(location = 0) in vec3 position;\nlayout(location = 1) in vec2 texcoord;\n\nout vec2 fragTexCoord;\n\nuniform mat4 mvp;\n\nvoid main()\n{\n    gl_Position = mvp * vec4(position, 1.0);\n    fragTexCoord = texcoord;\n}";
