#pragma once

// Auto-generated from cube.frag.glsl
// Do not edit this file manually

const char* const CUBE_FRAGMENT_SHADER = "#version 330 core\n\nin vec2 fragTexCoord;\nout vec4 finalColor;\n\nvoid main()\n{\n    finalColor = vec4(fragTexCoord.x, fragTexCoord.y, 0.5, 1.0);\n}";
