#pragma once

// Auto-generated from triangle.frag.glsl
// Do not edit this file manually

const char* const WIND_FRAGMENT_SHADER = "#version 330 core\n\nin vec3 fragColor;\nout vec4 finalColor;\n\nvoid main()\n{\n    finalColor = vec4(fragColor, 1.0);\n}";
